language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8
  - openjdk11
git:
  submodules: false
before_install:
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
  - ./paper patch
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work/Minecraft'
